packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - unrs-resolver
